from mysql.connector import errors

IntegrityError: errors.DatabaseError
